### ISSUE TITLE
Builder Generator uses static fields

### ISSUE THREAD

**Issue by bartmark** [helospark/SparkTools#1]
First of all, cool plugin for generating builders!

It would be nice to exclude static fields maybe at all or by configuration in preferences.
In my opinion it makes no sense to include static fields in the builder generation.

**Comment by helospark** [comment]
Hi bartmark!

Thanks for reporting this issue. Generating builder methods for static fields indeed makes little sense (and possibly compilation errors when the static field is also final), so following your advice I have filtered out all static fields from builder method generation in [29e35e0](https://github.com/helospark/SparkTools/commit/29e35e0086fd377c2f10be6e7c6a4bd2c539ccb7).
It has been released as version 0.0.2 you can now update it on Eclipse marketplace.
