### ISSUE TITLE
Support of nested class

### ISSUE THREAD

**Issue by Rapster** [helospark/SparkTools#10]
Hi there,

I have a nested class, and I'd like to generate a builder of it. But, it does generate the builder for the "parent" class, not the nested one. 

Thanks for your work

**Comment by helospark** [comment]
Hey Rapster,

I'm wondering if the internal classes could be static and nonstatic as well in your usecase.
In Java nonstatic nested classes cannot have static methods, which would change the usage of the builder quite a bit, you would not be able to use:
NestedClass.builder().with....
Instead you would have to build a class with new
instance.new Builder().with...

Not to mention if you would want to access the builder on an instance outside of the outer class you would have to write the following blasphemy:
new EnclosingClass().new NestedClass().new Builder().with...
:smile_cat:

To me builder for nonstatic nested classes does not make much sense.

**Comment by helospark** [comment]
Hi Rapster,

Support to generate builder based on the currently selected class (cursors position) is added to version **0.0.9**. Based on my above comment nonstatic nested classes are ignored.

Please update and check if it works as expected.
