### ISSUE TITLE
Option for Staged Builder

### ISSUE THREAD

**Issue by chris-koester** [helospark/SparkTools#4]
It would be great to have an option to generate a "staged builder" (which basically defines interfaces for the order in which methods should be called by the client).

The idea is discussed in the following blog post:
http://blog.crisp.se/2013/10/09/perlundholm/another-builder-pattern-for-java

The immutables-project also has an option for this (but can not be used in all projects):
https://immutables.github.io/immutable.html#staged-builder

**Comment by helospark** [comment]
Hi chris-koester!
Staged builder is added to version **0.0.6**.
Please update and try if it works as expected.
