### ISSUE TITLE
Can this builder work (or be made to work) with class hierarchies?

### ISSUE THREAD

**Issue by andrewliles** [helospark/SparkTools#7]
e.g.
```
abstract class Parent { int a }
class Child extends Parent { String s }
```

I want to be build an instance of Child - please can you tell me if this is possible

**Comment by helospark** [comment]
Hi Andrew,

It is not possible at the moment, but thank you for the report! This enhancement will be added to the plugin.

**Comment by andrewliles** [comment]
Anything I can do to contribute?  I would need to know where you introspect the class

**Comment by helospark** [comment]
Sure you can, any help is appreciated :)
Extracting the field is done in here:
https://github.com/helospark/SparkTools/blob/b2ca42b377f7b16107751752921552dc9200263c/SparkBuilderGeneratorPlugin/src/com/helospark/spark/builder/handlers/codegenerator/ApplicableBuilderFieldExtractor.java
_(Note: this is a link to a branch, as I'm in the process of a slight refactor as part of issue #4, though this part of the code will not be too much affected, on master this file is called ApplicableBuilderFieldConverter)._
This class gets the original class and returns a list of fields to add to the builder. This seems like a pretty good place to place the code to iterate over on all superclasses and collect all the fields.

Some things, which I think will be a bit more challenging:

 - typeDeclaration.getSuperClass() is not a TypeDeclaration where fields can be extracted, I think it has to be matched to a concrete ICompilationUnit and AST has to be parsed.
 - Field's scope in the superclass has to be checked, whether it's actually accessible in the child class (default scope only accessible when it's in the same package, private never, protected and public always)
 - Integration test cannot handle ICompilationUnit, so it will need to be made to be mocked

**Comment by andrewliles** [comment]
Hmm... since I have never worked with AST this might be beyond me.

I have imported the 3 projects into my workspace and each of them has got compilation errors.  Do you have any notes on get going, please?

**Comment by helospark** [comment]
You have to install Plugin Development Environment (PDE) Eclipse plugin, there should not be any other step.
It is enough to open SparkBuilderGenerator root project for the development (you might need to set TestNg, Mockito and JCommander jar's path in the project's settings to be able to run tests). After it you should be able to run the project by just "Run as Eclipse application".

**Comment by helospark** [comment]
Hey Andrew,

Are you working on this? If not, I can start it, as I have finished with the staged builder.

**Comment by andrewliles** [comment]
Hi,

Frankly, I have not made any headway on this.  Sorry to give you false hope.

In BuilderPatternCodeGenerator, I got this far and then couldn't work 
out how to get a TypeDeclaration from a ITypeBinding...


     private List<NamedVariableDeclarationField> 
collectBuildableFields(TypeDeclaration typeDecl) {
         FieldDeclaration[] fields = typeDecl.getFields();
         List<NamedVariableDeclarationField> answer = 
applicableBuilderFieldConverter.convertApplicableFields(fields);

         if(HANDLE_SUPERCLASS) {
             // http://stackoverflow.com/a/20902865/1847378
             ITypeBinding superBinding = 
typeDecl.resolveBinding().getSuperclass();
             if((superBinding!=null) && 
(superBinding.getTypeDeclaration()!=null)) {
                 TypeDeclaration superType = 
superBinding.getTypeDeclaration();

                 answer.addAll(collectBuildableFields(typeDecl));
             }
         }
         return answer;
     }

**Comment by helospark** [comment]
Don't apologize, I really appreciate the effort! :1st_place_medal: 

Unfortunately the documentation and the information about Eclipse plugin programming is indeed quite scarce. While searching about this problem I have also came across the same Stackoverflow as you have :laughing: 

You were really close, after several hours of Googleing I found that the trick is that the binding contains an IType, which could be parsed by the CompilationUnitParser already contained in the project:
```
IType type = (IType) superTypeBinding.getJavaElement();
ICompilationUnit compilationUnit = compilationUnitParser.parse(type.getCompilationUnit());
TypeDeclaration typeDeclaration = findMatchingTypeByName(compilationUnit.types(), type)
```

**Comment by helospark** [comment]
Hi Andrew,

Support for type hierarchy was added to version *0.0.7*.
Please update and check if it works as expected.

**Comment by andrewliles** [comment]
I am unable to install version the latest version of the plugin (now 0.0.10).  I appreciate that this is probably a Marketplace configuration matter.

I am see 0.0.10 is referenced in ftp://helospark.com/eclipse_plugin/SparkBuilderGeneratorPlugin/
and when I view the Marketplace listing, SparkBuilderGenerator is listed as 0.0.10 but it will not upgrade.

I have subsequently tried uninstall / re-install but this re-installs the version I had before (0.0.4).  

Having done an uninstall, these are the steps:

1. Launch Eclipse Marketplace
1. Search for SparkG, hit enter
1. Single result, notice version number is 0.0.10
1. Click Install
1. Click Finish
1. On question about installing unsigned content, click Details>>
1. Notice that a v0.0.4 version is referenced:
    1. `/Users/a/.p2/pool/plugins/com.helospark.SparkBuilderGenerator_0.0.4.201612151818.jar`
    1. `/Users/a/.p2/pool/features/com.helospark.SparkBuilderGeneratorFeature_0.0.4.201612151818`

Then I located `~/.p2/pool/artifacts.xml` and removed both references to SparkBuilder assets.

Still no joy... seems to me that the Marketplace configuration needs to be updated on my machine

**Comment by helospark** [comment]
I can see couple of installs with 0.0.4 version in the log, so there appears to be a problem, that causes some Eclipses to see 0.0.4 version as the most recent.
If you know, could you tell me which version of the builder generator did you have before you tried to update to 0.0.10?

I will try to figure out, what could be the problem, until then you can install a specific version of the plugin directly, by
 - Help->Install new software
 - add a site with url: "ftp://helospark.com/eclipse_plugin/SparkBuilderGeneratorPlugin/" and any name
 - Uncheck "only show latest version"
 - You can select any version you would like to install

**Comment by helospark** [comment]
Also which Eclipse version are you using? An additional OSGI bundle import has been added to 0.0.5, which (might?) not be supported by your Eclipse and that could be why Eclipse refuse to update.
I cannot see other configuration change that might cause such problem in the PR.
My other though is that it might be caching related.

**Comment by andrewliles** [comment]
I am using

* Version: Neon Release (4.6.0)
* Build id: 20160613-1800

When I try to install via the direct FTP link you list, I am only offered 0.0.4:
![screenshot](http://www.starfishzone.com/temp/SparkBuilderPluginIssue.png)
