### ISSUE TITLE
How do I get the builder generator to include only specific fields?

### ISSUE THREAD

**Issue by ccleve** [helospark/SparkTools#8]
Hitting the button generates options for all private fields, which is not what I want.

**Comment by helospark** [comment]
At the moment there is no such feature, it always generates builder methods for all fields.
But thanks for the feedback, it will be added as an enhancement.

**Comment by helospark** [comment]
Hi ccleve,

Your requested feature is added to version **0.0.10**.

By default it is turned off, as the most common usage is to generate builder for all fields, but you can turn it on in the preferences (Window->Preferences->Java->Spark Builder Generator and check "Show dialog to filter which fields are included in the builder")

Please update and check if it works as expected.
